#! /usr/bin/bash
B="HID 256c:006e"
T="$B Pad pad"

# xsetwacom set $T Button 1
# xsetwacom set $T Button 2

# xsetwacom set $T Button 3
# xsetwacom set $T Button 8

# xsetwacom set $T Button 9
# xsetwacom set $T Button 10


xsetwacom set $T Button 11 "key f14"
# xsetwacom set $T Button 12

# xsetwacom set $T Button 13
# xsetwacom set $T Button 14

# xsetwacom set $T Button 15
# xsetwacom set $T Button 16

S="$B Pen stylus"

xsetwacom set $S Button 2 "key e"