stores:
    .config:
        ghostty:
            target: ~/.config/ghostty
        helix:
            target: ~/.config/helix
        k9s:
            target: ~/.config/k9s
        kitty:
            target: ~/.config/kitty
            files:
                - kitty.conf
        pipewire/pipewire.conf.d:
            target: ~/.config/pipewire/pipewire.conf.d
            patterns:
                - "*"
        systemd:
            user:
                target: ~/.config/systemd/user
                patterns:
                    - "*"
        zellij:
            target: ~/.config/zellij
    bin:
        target: ~/.local/bin
        patterns:
            - "*"
    config:
        MangoHud:
            target: ~/.config/MangoHud
        kanata:
            target: ~/.config/kanata
        kube:
            target: ~/.kube
            files:
                - kubie.yaml
        mprocs:
            target: ~/.config/mprocs
        niri:
            target: ~/.config/niri
        nvim:
            target: ~/.config/nvim
        starship:
            target: ~/.config
            files:
                - starship.toml
        yazi:
            target: ~/.config/yazi
