theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "multiple"
rulers = [80]
shell = ["zsh", "-c"]
color-modes = true
true-color = true

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "all"
newline = "all"
tab = "all"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
j = { k = "normal_mode", j = "normal_mode" }

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
